### ISSUE TITLE
Refactor pages to use Bootstrap

### ISSUE THREAD

**Issue by jtn7** [jtn7/it490_project#1]
Remake each page including the header and footer so that all pages have consistent styling.

- [x] Pages should make use of easy to use styling and arrangement through the [Bootstrap framework](https://getbootstrap.com/).
- [x] Naming conventions should also be followed for classes and IDs of elements.
    * [Search result for naming conventions](https://stackoverflow.com/questions/1696864/naming-class-and-id-html-attributes-dashes-vs-underlines)
- [x] ~~All html/css/js files should now live in the `/front/html` directory~~ 

## Current Pages
* [Login](https://github.com/jtn7/it490_project/blob/development/front/login.php)
* [Signup](https://github.com/jtn7/it490_project/blob/development/front/signup.php)
* [Index](https://github.com/jtn7/it490_project/blob/development/front/index.php)
* [Character Creation](https://github.com/jtn7/it490_project/blob/development/front/createCharacter.php)
* [Forums](https://github.com/jtn7/it490_project/blob/development/front/forums.php)
* [Threads](https://github.com/jtn7/it490_project/blob/development/front/threads.php)
* [Thread Creation](https://github.com/jtn7/it490_project/blob/development/front/createThread.php)
* [Replies](https://github.com/jtn7/it490_project/blob/development/front/replies.php)

**Comment by jtn7** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remake the HTML and CSS for frontend pages](https://trello.com/c/Xp42RQKa/1-remake-the-html-and-css-for-frontend-pages)

**Comment by marvinJung** [comment]
Naming conventions and previous names untouched, any issue that may arise can be resolved.

**Comment by marvinJung** [comment]
The file directory may need to be organized and merged with the development branch soon.

**Comment by marvinJung** [comment]
Resolved & frontEnd branch has been merged to development branch.
